// Updated MPD Layer using explicit HTML formatting
const mpdLayer = L.geoJSON(null, {
    style: getMpdStyle,
    onEachFeature: function (feature, layer) {
        const props = feature.properties;
        
        // Ensure we are only applying this to MPDs
        if (props && props.dataType === "MPD") {
            
            // Pull the clean metadata generated by our Python script
            const mpdNum = props.mpd_number || "Unknown";
            const mpdTag = props.mpd_tag || "See WPC for details";
            const validTime = props.valid_time || "Unknown";

            // 1. The Hover Tooltip (3 clean, centered lines)
            const tooltipHTML = `
                <div style="text-align: center; font-family: sans-serif; line-height: 1.4;">
                    <strong>MPD ${mpdNum}</strong><br>
                    ${mpdTag}<br>
                    Valid: ${validTime}
                </div>
            `;
            
            layer.bindTooltip(tooltipHTML, {
                sticky: true,
                direction: "top"
            });
            
            // 2. The Clickable Popup (Given a min-width so it never squishes vertically)
            const popupHTML = `
                <div style="font-family: sans-serif; font-size: 14px; min-width: 240px; text-align: center;">
                    <strong>MPD ${mpdNum}</strong><br>
                    <span style="color: #d84b2a;"><strong>${mpdTag}</strong></span><br>
                    <hr style="margin: 5px 0;">
                    <span style="font-size: 0.9em;">Valid: ${validTime}</span>
                </div>
            `;
            
            layer.bindPopup(popupHTML);
        }
    }
});
